WellCommerce\Bundle\AppBundle\Entity\Channel:
    type: entity
    table: smuggler_channel
    repositoryClass: WellCommerce\Bundle\AppBundle\Repository\ChannelRepository
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
        url:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
    lifecycleCallbacks: {  }
