well_commerce_smuggler:
    services:
        channel:
            auto_services:
                factory: WellCommerce\Bundle\SmugglerBundle\Factory\ChannelFactory
                repository: WellCommerce\Bundle\SmugglerBundle\Repository\ChannelRepository
            orm_configuration:
                mapping: "@WellCommerceSmugglerBundle/Resources/config/doctrine/Channel.orm.yml"
                entity: WellCommerce\Bundle\SmugglerBundle\Entity\Channel
        package:
            auto_services:
                factory: WellCommerce\Bundle\SmugglerBundle\Factory\PackageFactory
                repository: WellCommerce\Bundle\SmugglerBundle\Repository\PackageRepository
            orm_configuration:
                mapping: "@WellCommerceSmugglerBundle/Resources/config/doctrine/Package.orm.yml"
                entity: WellCommerce\Bundle\SmugglerBundle\Entity\Package
