well_commerce_app:
    services:
        admin_menu:
            auto_services:
                factory: WellCommerce\Bundle\AdminBundle\Factory\AdminMenuFactory
                repository: WellCommerce\Bundle\AdminBundle\Repository\AdminMenuRepository
            orm_configuration:
                mapping: "@WellCommerceAdminBundle/Resources/config/doctrine/AdminMenu.orm.yml"
                entity: WellCommerce\Bundle\AdminBundle\Entity\AdminMenu
